### ISSUE TITLE
dpkg  fails under Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by minorsatellite** [rouben/zfswatcher#12] opened 2020-01-28 18:42 UTC
Attempting to install zfswatcher_0.03-2_amd64.deb package on Ubuntu 18.04 fails with the following error:

```
Selecting previously unselected package zfswatcher.
(Reading database ... 147733 files and directories currently installed.)
Preparing to unpack zfswatcher_0.03-2_amd64.deb ...
Unpacking zfswatcher (0.03-2) ...
dpkg: dependency problems prevent configuration of zfswatcher:
 zfswatcher depends on zfs | ubuntu-zfs | debian-zfs; however:
  Package zfs is not installed.
  Package ubuntu-zfs is not installed.
  Package debian-zfs is not installed.

dpkg: error processing package zfswatcher (--install):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Processing triggers for ureadahead (0.100.0-21) ...
ureadahead will be reprofiled on next reboot
Processing triggers for systemd (237-3ubuntu10.21) ...
Errors were encountered while processing:
 zfswatcher
```

Attempting to install from source results in similar error.

**Comment by rouben** [comment] 2020-02-02 00:12
0.03 uses a different dependency nomenclature that was later fixed. Please use the latest release.

This is a duplicate of #8

**Closed as completed by rouben** 2020-02-02 00:12 UTC
Labels: duplicate, wontfix
